config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :matches
  resources :venues
  resources :players
  resources :teams
  get 'home_pages/home'

  get 'home_pages/about'

  root 'home_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :teams
  belongs_to :venue

  validates :title, :presence => true, :uniqueness => false
  validates :team1_id, :presence => true, :uniqueness => false
  validates :team2_id, :presence => true, :uniqueness => false
  validates :venue_id, :presence => true, :uniqueness => false
  validates :schedule, :presence => true, :uniqueness => false
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    #@matches = Match.all
    @matches = Match.order('schedule ASC')
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    if @match.team1_id == @match.team2_id
      flash[:notice] = "Team1 and team 2 are same"
      redirect_to new_match_url
    else
      respond_to do |format|
        if @match.save
          format.html { redirect_to matches_url, notice: 'Match was successfully created.' }
          format.json { render :show, status: :created, location: @match }
        else
          format.html { render :new }
          format.json { render json: @match.errors, status: :unprocessable_entity }
        end
      end
    end
=begin
    respond_to do |format|
      if @match.save
        format.html { redirect_to matches_url, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to matches_url, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:title, :team1_id, :team2_id, :venue_id, :schedule)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, :placeholder => 'Team 1 vs Team 2', id: :match_title %>
  </div>

  <div class="field">
    <%= form.label :team1_id %>
    <%= form.select(:team1_id, team_names_list, :prompt => 'Select Team 1') %><br><br>
    <%# form.number_field :team1_id, id: :match_team1_id %>
  </div>

  <div class="field">
    <%= form.label :team2_id %>
    <%= form.select(:team2_id, team_names_list, :prompt => 'Select Team 2') %><br><br>
    <%# form.number_field :team2_id, id: :match_team2_id %>
  </div>

  <div class="field">
    <%= form.label :venue_id %>
    <%= form.select(:venue_id, venue_names_list, :prompt => 'Select Venue') %><br><br>
    <%# form.number_field :venue_id, id: :match_venue_id %>
  </div>

  <div class="field">
    <%= form.label :schedule %>
    <%= form.date_field :schedule, min: Date.today, id: :match_schedule %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  $(function() {
    $( "#schedule" ).datepicker();
  });
</script>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Matches</h1>

<div class="container">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Team1</th>
      <th>Team2</th>
      <th>Venue</th>
      <th>Schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.title %></td>
        <td><%= team_name_finder(match.team1_id) %></td>
        <td><%= team_name_finder(match.team2_id) %></td>
        <td><%= match.venue.location %></td>
        <td><%= match.schedule %></td>
        <td><%# link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<h3>Captain: <%= find_captain(@match.id) %></h3>
<h3>GoalKeeper: <%= find_goalkeeper(@match.id) %></h3>

<p>
  <strong>Team1:</strong>
  <%# @match.team1_id %>
  <%= team_name_finder(@match.team1_id) %>
</p>

<p>
  <strong>Team2:</strong>
  <%= team_name_finder(@match.team2_id) %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @match.venue.location %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @match.schedule %>
</p>

<p> <%= find_captain(@match.id) %>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>