config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :matches
  resources :venues
  resources :players
  resources :teams
  get 'home_pages/home'

  get 'home_pages/about'

  root 'home_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FootBall', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Homepage', root_path %></li>
        <li><%= link_to 'Match', matches_path %></li>
        <li><%= link_to 'Teams', teams_path %></li>
        <li><%= link_to 'All Players', players_path %></li>
        <li><%= link_to 'Venue', venues_path %></li>
        <li><%= link_to 'roles', roles_path %></li>
        <li><%# link_to 'About', static_pages_about_path %></li>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Football</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= bootstrap_flash %>
    <div class="container">
        <%= yield %>
    </div>
        <%# render 'layouts/foot' %>
  </body>
</html>